# Generated by Django 5.1.2 on 2024-11-24 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name': 'Property', 'verbose_name_plural': 'Properties'},
        ),
        migrations.RenameField(
            model_name='property',
            old_name='name',
            new_name='my_name',
        ),
        migrations.RenameField(
            model_name='unit',
            old_name='property_type',
            new_name='property',
        ),
        migrations.RemoveField(
            model_name='property',
            name='number_unit',
        ),
        migrations.AddField(
            model_name='property',
            name='number_of_units',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('commercial', 'commercial'), ('residential', 'residential'), ('apartment', 'apartment')], max_length=100),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
